name = "sutaba-tracker-pages"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sutaba-db"
database_id = "d3506cb0-5234-4b3b-88f6-7b81408f26e3"
